export let product = [
  {
    id: 1,
    title: "POWERIMPACT TRAINING MEDIUM-SUPPORT BRA",
    desc: "Give it your all. It's time to throw down, and this adidas bra is what you want on when you do. From HIIT training to heart-pumping sessions on the bike — targeted mesh panels increase airflow for cool relief as the heat builds. Sleek adiflex has a slick, cool-to-the-touch feel. AEROREADY technology is there to help you stay dry and comfortable too. No chafing here. The purposeful design makes sure of it.",
    img: "./bra.png",
    price: 110,
  },
  {
    id: 2,
    title: "HP Spectre Foldable PC 17",
    desc: "You can harness your full potential with an HP Spectre that packs an Intel® Core™ i7 processor, up to 32GB of memory, a dazzling high-resolution display, and the boundless features of the latest version of Windows 11 Pro or Home. You can harness your full potential with an HP Spectre that packs an Intel® Core™ i7 processor, up to 32GB of memory, a dazzling high-resolution display, and the boundless features of the latest version of Windows 11 Pro or Home.",
    img: "./hp.avif",
    price: 1920,
  },
  {
    id: 3,
    title: "Iphone-14 pro-max",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae, provident expedita excepturi distinctio atque earum molestias veritatis, ex necessitatibus delectus aliquid reiciendis consectetur eaque ratione obcaecati asperiores. Eligendi distinctio voluptates et quam neque. Eius, tempora natus nemo voluptatum quibusdam architecto ex temporibus, officiis itaque quas ab animi optio recusandae modi!",
    img: "./iphone.png",
    price: 1200,
  },
  {
    id: 4,
    title: "Jacket",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae, provident expedita excepturi distinctio atque earum molestias veritatis, ex necessitatibus delectus aliquid reiciendis consectetur eaque ratione obcaecati asperiores. Eligendi distinctio voluptates et quam neque. Eius, tempora natus nemo voluptatum quibusdam architecto ex temporibus, officiis itaque quas ab animi optio recusandae modi!",
    img: "./jacket.png",
    price: 112,
  },
  {
    id: 5,
    title: "Jeans | Full-out wear",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae, provident expedita excepturi distinctio atque earum molestias veritatis, ex necessitatibus delectus aliquid reiciendis consectetur eaque ratione obcaecati asperiores. Eligendi distinctio voluptates et quam neque. Eius, tempora natus nemo voluptatum quibusdam architecto ex temporibus, officiis itaque quas ab animi optio recusandae modi!",
    img: "./jeans.png",
    price: 129,
  },
  {
    id: 6,
    title: "Mac-Book Pro 16.inc",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae, provident expedita excepturi distinctio atque earum molestias veritatis, ex necessitatibus delectus aliquid reiciendis consectetur eaque ratione obcaecati asperiores. Eligendi distinctio voluptates et quam neque. Eius, tempora natus nemo voluptatum quibusdam architecto ex temporibus, officiis itaque quas ab animi optio recusandae modi!",
    img: "./mac.png",
    price: 3099.99,
  },
  {
    id: 7,
    title: "Rolex-Phantom R-C12",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae, provident expedita excepturi distinctio atque earum molestias veritatis, ex necessitatibus delectus aliquid reiciendis consectetur eaque ratione obcaecati asperiores. Eligendi distinctio voluptates et quam neque. Eius, tempora natus nemo voluptatum quibusdam architecto ex temporibus, officiis itaque quas ab animi optio recusandae modi!",
    img: "rolex.webp",
    price: 26999.9,
  },
  {
    id: 8,
    title: "Samsung-S21 ultra",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae, provident expedita excepturi distinctio atque earum molestias veritatis, ex necessitatibus delectus aliquid reiciendis consectetur eaque ratione obcaecati asperiores. Eligendi distinctio voluptates et quam neque. Eius, tempora natus nemo voluptatum quibusdam architecto ex temporibus, officiis itaque quas ab animi optio recusandae modi!",
    img: "./samsung.png",
    price: 989.99,
  },
  {
    id: 9,
    title: "Nike-BrandNew Shoe",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae, provident expedita excepturi distinctio atque earum molestias veritatis, ex necessitatibus delectus aliquid reiciendis consectetur eaque ratione obcaecati asperiores. Eligendi distinctio voluptates et quam neque. Eius, tempora natus nemo voluptatum quibusdam architecto ex temporibus, officiis itaque quas ab animi optio recusandae modi!",
    img: "./shoe.png",
    price: 120,
  },
  {
    id: 10,
    title: "Aluva-Short Short",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae, provident expedita excepturi distinctio atque earum molestias veritatis, ex necessitatibus delectus aliquid reiciendis consectetur eaque ratione obcaecati asperiores. Eligendi distinctio voluptates et quam neque. Eius, tempora natus nemo voluptatum quibusdam architecto ex temporibus, officiis itaque quas ab animi optio recusandae modi!",
    img: "./short.png",
    price: 89.98,
  },
  {
    id: 11,
    title: "Slipper-Ergo",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae, provident expedita excepturi distinctio atque earum molestias veritatis, ex necessitatibus delectus aliquid reiciendis consectetur eaque ratione obcaecati asperiores. Eligendi distinctio voluptates et quam neque. Eius, tempora natus nemo voluptatum quibusdam architecto ex temporibus, officiis itaque quas ab animi optio recusandae modi!",
    img: "./slipper.png",
    price: 12.99,
  },
  {
    id: 12,
    title: "Konka-Refridgerator",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae, provident expedita excepturi distinctio atque earum molestias veritatis, ex necessitatibus delectus aliquid reiciendis consectetur eaque ratione obcaecati asperiores. Eligendi distinctio voluptates et quam neque. Eius, tempora natus nemo voluptatum quibusdam architecto ex temporibus, officiis itaque quas ab animi optio recusandae modi!",
    img: "./fridge.png",
    price: 2097.99,
  },
  {
    id: 13,
    title: "Samsung-a34",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae, provident expedita excepturi distinctio atque earum molestias veritatis, ex necessitatibus delectus aliquid reiciendis consectetur eaque ratione obcaecati asperiores. Eligendi distinctio voluptates et quam neque. Eius, tempora natus nemo voluptatum quibusdam architecto ex temporibus, officiis itaque quas ab animi optio recusandae modi!",
    img: "./a34.png",
    price: 877.99,
  },
  {
    id: 14,
    title: "Vonos-Bycycle-FU",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae, provident expedita excepturi distinctio atque earum molestias veritatis, ex necessitatibus delectus aliquid reiciendis consectetur eaque ratione obcaecati asperiores. Eligendi distinctio voluptates et quam neque. Eius, tempora natus nemo voluptatum quibusdam architecto ex temporibus, officiis itaque quas ab animi optio recusandae modi!",
    img: "./bycycle.png",
    price: 477.99,
  },
  {
    id: 14,
    title: "Smuorai-Real-Estate",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae, provident expedita excepturi distinctio atque earum molestias veritatis, ex necessitatibus delectus aliquid reiciendis consectetur eaque ratione obcaecati asperiores. Eligendi distinctio voluptates et quam neque. Eius, tempora natus nemo voluptatum quibusdam architecto ex temporibus, officiis itaque quas ab animi optio recusandae modi!",
    img: "./house.png",
    price: 1099990.99,
  },
];
//https://assets.mora-appliances.com/images/1_25_09_09_2022-070350.png